server:
  port: 8084
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    databse-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: true
    properties:
      hibernate.ddl-auto: create-drop
      hibernate.connection.provider_disables_autocommit: true